apiVersion: v1
kind: ConfigMap
metadata:
  name: karpenter-skroobapi-config
  namespace: HCP_NAMESPACE
data:
  skroobapi.yaml: |
  # Minimal debug configuration
  defaultKubeconfig: "incluster"

  mappings:
    # Route Deployments in default namespace to a specific cluster
    #- group: "apps"
    #  version: "v1"
   #   kind: "Deployment"
   #   namespace: "default"
   #   kubeconfig: "/mnt/kubeconfig/target-kubeconfig"
   #   priority: 100

    - group: ""
      version: "v1"
      kind: "Node"
      kubeconfig: "/mnt/kubeconfig/target-kubeconfig"
      priority: 150 

    # Route Karpenter NodePools to karpenter cluster
    # Example of ForceClusterScopedToNamespace: if NodePools are cluster-scoped
    # in the source cluster but namespaced in the target cluster
    - group: "karpenter.sh"
      version: "v1"
      kind: "NodePool"
      kubeconfig: "/mnt/kubeconfig/target-kubeconfig"
      priority: 200
      forceClusterScopedToNamespace: "karpenter-system"

    # Route Karpenter NodeClaims to karpenter cluster
    - group: "karpenter.sh"
      version: "v1"
      kind: "NodeClaim"
      kubeconfig: "/mnt/kubeconfig/target-kubeconfig"
      priority: 200

    # Route AWS-specific Karpenter resources to karpenter cluster
    # TODO(jkyros): I think we're leaving this in management namespace for now
    #- group: "karpenter.k8s.aws"
    #  version: "v1"
    #  kind: "EC2NodeClass"
    #  kubeconfig: "/mnt/kubeconfig/target-kubeconfig"
    #  priority: 200

  